# Generated by Django 5.1.3 on 2024-11-29 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=36, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=36, message='The merchant id must be at least 36 characters.'), django.core.validators.MaxLengthValidator(limit_value=36, message='The merchant id must not be greater than 36 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=36, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('callback_url', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('F', 'Failed')], default='P', max_length=1)),
                ('verified', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchant')),
            ],
        ),
    ]
